### ISSUE TITLE
Create default PHPUnit configuration

### ISSUE THREAD

**Issue by shadowhand** [http-interop/http-factory-tests#3]
The PHPUnit configuration described in README can be transferred to a `phpunit.xml.dist` file.

**Comment by Nyholm** [comment]
They are: https://github.com/http-interop/http-factory-guzzle/blob/master/phpunit.xml.dist#L8

They can't be in a `phpunit.xml.dist` file in this repo because you will never run the tests here.

**Comment by shadowhand** [comment]
My mistake, I forgot this package gets reused by implementations!
