### ISSUE TITLE
Tests for StreamFactoryInterface::createStreamFromResource

### ISSUE THREAD

**Issue by Zegnat** [http-interop/http-factory-tests#37]
You’ll notice that there were no additional tests for this method in #36. This is because I am not sure I understand the PSR-17 Docblock. I have just [posted about this to the PHP-FIG mailing list](https://groups.google.com/forum/#!topic/php-fig/ThSxlGT8i14).

At one point I had the following test:

```php
    public function testCreateStreamFromWriteOnlyResource()
    {
        $file = $this->createTemporaryFile();
        $resource = fopen($file, 'w');
        $string = 'would you like some crumpets?';
        fwrite($resource, $string);

        $stream = $this->factory->createStreamFromResource($resource);

        $this->assertEquals(true, $stream->isReadable());
        $stream->read(1);
    }
```

This would ascertain the Stream to be readable, even when created from a write-only resource. [Nyholm/psr7](https://github.com/Nyholm/psr7) will fail this test, I haven’t checked other implementations yet.

Is this test correct? Is my reading of PSR-17 wrong? Or is the PSR wrong in that it requires a readable stream as output?

Either way: that part of the test case may still need some work!

**Comment by shadowhand** [comment]
Fixed by #39.
