### ISSUE TITLE
Inconsistency in namespace 

### ISSUE THREAD

**Issue by harikt** [http-interop/http-factory-tests#4]
Hi, 

I wonder why there is an inconsistency in the namespace . 

https://github.com/http-interop/http-factory/blob/380fd6d00139cd3ad92b32a8d63ee07eaa39dd9f/src/RequestFactoryInterface.php#L3 on `Interop` and https://github.com/http-interop/http-factory-tests/blob/6ceaf2c45e4c890f634343b94bb4e74cee5e5b83/src/RequestFactoryTest.php#L3 on `Http`

**Comment by Nyholm** [comment]
There is no reason. It is me who wrote a typo. It should be Interop.
