### ISSUE TITLE
Separate tests from factory object instantiation

### ISSUE THREAD

**Issue by sagikazarmark** [http-interop/http-factory-tests#5]
Currently the only way to run these tests is to define those constants.

What if there is more configuration needed in the constructor of the factory? What if there are more than one factory of the same type to test? What if someone wants to test something extra (although that might break SRP, but still)?

Although these does not sound to common cases, but I think separating the current tests from the bootstrap logic itself is a sane argument. I would split all tests into two parts:

- one to be the "reusable" tests
- one to be the bootstrapped one using the constants

I would put them into separate namespaces, so that the current PHPUnit configuration could still work.

WDYT?

I am happy to provide a PR.

**Comment by shadowhand** [comment]
I'm interested to see what this looks like.

**Comment by Nyholm** [comment]
:+1:
